# Generated by Django 5.1.3 on 2024-12-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_date", models.DateField(verbose_name="入住日期")),
                ("check_out_date", models.DateField(verbose_name="退房日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待确认"),
                            ("confirmed", "已确认"),
                            ("checked_in", "已入住"),
                            ("checked_out", "已退房"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "住宿安排",
                "verbose_name_plural": "住宿安排",
            },
        ),
        migrations.CreateModel(
            name="CheckInRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_in_type",
                    models.CharField(
                        choices=[
                            ("regular", "常规签到"),
                            ("late", "迟到签到"),
                            ("manual", "人工签到"),
                        ],
                        default="regular",
                        max_length=20,
                        verbose_name="签到类型",
                    ),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="签到时间"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "签到记录",
                "verbose_name_plural": "签到记录",
                "ordering": ["-check_in_time"],
            },
        ),
        migrations.CreateModel(
            name="CheckInStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="站点名称")),
                ("location", models.CharField(max_length=200, verbose_name="位置")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "签到站点",
                "verbose_name_plural": "签到站点",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="公司名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="公司编码"
                    ),
                ),
                (
                    "business_type",
                    models.CharField(max_length=100, verbose_name="业务类型"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "公司",
                "verbose_name_plural": "公司",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="会议名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="会议代码"
                    ),
                ),
                ("description", models.TextField(verbose_name="会议描述")),
                ("organizer", models.CharField(max_length=200, verbose_name="主办方")),
                ("start_date", models.DateTimeField(verbose_name="会议开始时间")),
                ("end_date", models.DateTimeField(verbose_name="会议结束时间")),
                (
                    "registration_start",
                    models.DateTimeField(verbose_name="报名开始时间"),
                ),
                ("registration_end", models.DateTimeField(verbose_name="报名截止时间")),
                ("check_in_start", models.DateTimeField(verbose_name="签到开始时间")),
                ("check_in_end", models.DateTimeField(verbose_name="签到结束时间")),
                (
                    "venue_name",
                    models.CharField(max_length=200, verbose_name="会议地点名称"),
                ),
                ("venue_address", models.TextField(verbose_name="会议地点详细地址")),
                (
                    "min_participants",
                    models.IntegerField(default=1, verbose_name="最少参会人数"),
                ),
                ("max_participants", models.IntegerField(verbose_name="最大参会人数")),
                (
                    "company_min_participants",
                    models.IntegerField(default=1, verbose_name="每家公司最少参会人数"),
                ),
                (
                    "company_max_participants",
                    models.IntegerField(verbose_name="每家公司最大参会人数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("registration", "报名中"),
                            ("registration_ended", "报名结束"),
                            ("check_in", "签到中"),
                            ("in_progress", "进行中"),
                            ("completed", "已结束"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="会议状态",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="是否公开"),
                ),
                (
                    "require_approval",
                    models.BooleanField(default=False, verbose_name="是否需要审核"),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=100, verbose_name="联系人"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="联系电话"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="联系邮箱"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="附加信息"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "会议活动",
                "verbose_name_plural": "会议活动",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "title",
                    models.CharField(blank=True, max_length=100, verbose_name="职位"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="电话")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="联系人的其他信息，如负责的具体事项等",
                        verbose_name="描述",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="主要联系人"),
                ),
            ],
            options={
                "verbose_name": "联系人",
                "verbose_name_plural": "联系人列表",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=100, verbose_name="职位")),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="是否为主要联系人"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "联系人",
                "verbose_name_plural": "联系人",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FieldLogicRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("equals", "等于"),
                            ("not_equals", "不等于"),
                            ("contains", "包含"),
                            ("not_contains", "不包含"),
                            ("greater_than", "大于"),
                            ("less_than", "小于"),
                            ("in", "在列表中"),
                            ("not_in", "不在列表中"),
                            ("starts_with", "以...开头"),
                            ("ends_with", "以...结尾"),
                            ("is_empty", "为空"),
                            ("is_not_empty", "不为空"),
                            ("between", "在...之间"),
                        ],
                        max_length=20,
                        verbose_name="运算符",
                    ),
                ),
                (
                    "value",
                    models.JSONField(blank=True, null=True, verbose_name="比较值"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("show", "显示"),
                            ("hide", "隐藏"),
                            ("enable", "启用"),
                            ("disable", "禁用"),
                            ("require", "必填"),
                            ("unrequire", "非必填"),
                            ("set_value", "设置值"),
                            ("clear_value", "清除值"),
                        ],
                        max_length=20,
                        verbose_name="执行动作",
                    ),
                ),
                (
                    "action_value",
                    models.JSONField(blank=True, null=True, verbose_name="动作值"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "condition_group",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="条件组"
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="优先级")),
            ],
            options={
                "verbose_name": "字段逻辑规则",
                "verbose_name_plural": "字段逻辑规则",
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="FieldOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="选项标签")),
                ("value", models.CharField(max_length=100, verbose_name="选项值")),
                ("order", models.IntegerField(verbose_name="显示顺序")),
                (
                    "is_exclusive",
                    models.BooleanField(default=False, verbose_name="是否互斥"),
                ),
                (
                    "max_selections",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="最大选择次数"
                    ),
                ),
            ],
            options={
                "verbose_name": "字段选项",
                "verbose_name_plural": "字段选项",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "单行文本"),
                            ("textarea", "多行文本"),
                            ("number", "数字"),
                            ("select", "下拉选择"),
                            ("radio", "单选"),
                            ("checkbox", "多选"),
                            ("date", "日期"),
                            ("time", "时间"),
                            ("file", "文件上传"),
                        ],
                        max_length=20,
                        verbose_name="字段类型",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="字段标签")),
                ("name", models.CharField(max_length=100, verbose_name="字段名称")),
                (
                    "placeholder",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="占位文本"
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="帮助文本"
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=True, verbose_name="是否必填"),
                ),
                ("order", models.IntegerField(verbose_name="显示顺序")),
                (
                    "validation_regex",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="验证规则"
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="错误提示"
                    ),
                ),
                (
                    "default_value",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="默认值"
                    ),
                ),
                (
                    "is_unique_in_company",
                    models.BooleanField(default=False, verbose_name="公司内唯一"),
                ),
                (
                    "max_occurrences",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="最大出现次数"
                    ),
                ),
            ],
            options={
                "verbose_name": "表单字段",
                "verbose_name_plural": "表单字段",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FormFieldResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(verbose_name="回复内容")),
            ],
            options={
                "verbose_name": "表单字段回复",
                "verbose_name_plural": "表单字段回复",
            },
        ),
        migrations.CreateModel(
            name="FormResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "表单回复",
                "verbose_name_plural": "表单回复",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="酒店名称")),
                ("address", models.TextField(verbose_name="详细地址")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="酒店描述"),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=100, verbose_name="联系人"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="联系电话"),
                ),
                ("star_rating", models.IntegerField(verbose_name="星级")),
            ],
            options={
                "verbose_name": "酒店",
                "verbose_name_plural": "酒店",
            },
        ),
        migrations.CreateModel(
            name="MaterialCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("badge", "胸卡"),
                            ("materials", "会议资料"),
                            ("gift", "礼品"),
                        ],
                        max_length=20,
                        verbose_name="物料类型",
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="领取时间"),
                ),
                (
                    "collected",
                    models.BooleanField(default=True, verbose_name="是否已领取"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "物料领取",
                "verbose_name_plural": "物料领取",
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "早餐"),
                            ("lunch", "午餐"),
                            ("dinner", "晚餐"),
                            ("tea_break", "茶歇"),
                        ],
                        max_length=20,
                        verbose_name="餐次类型",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("start_time", models.TimeField(verbose_name="开始时间")),
                ("end_time", models.TimeField(verbose_name="结束时间")),
                ("max_capacity", models.IntegerField(verbose_name="最大接待人数")),
            ],
            options={
                "verbose_name": "餐次",
                "verbose_name_plural": "餐次",
            },
        ),
        migrations.CreateModel(
            name="MealOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="选项名称")),
                (
                    "diet_type",
                    models.CharField(
                        choices=[
                            ("regular", "普通"),
                            ("vegetarian", "素食"),
                            ("halal", "清真"),
                            ("diabetes", "糖尿病餐"),
                        ],
                        default="regular",
                        max_length=20,
                        verbose_name="饮食类型",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                ("max_quantity", models.IntegerField(verbose_name="最大供应数量")),
            ],
            options={
                "verbose_name": "餐饮选项",
                "verbose_name_plural": "餐饮选项",
            },
        ),
        migrations.CreateModel(
            name="MealRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "已登记"),
                            ("attended", "已用餐"),
                            ("cancelled", "已取消"),
                        ],
                        default="registered",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "registration_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="登记时间"),
                ),
                (
                    "attendance_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="用餐时间"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "用餐登记",
                "verbose_name_plural": "用餐登记",
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("position", models.CharField(max_length=100, verbose_name="职位")),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待确认"),
                            ("confirmed", "已确认"),
                            ("checked_in", "已签到"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="登记编号"
                    ),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="签到时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "参会人员",
                "verbose_name_plural": "参会人员",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("confirmed", "已确认"),
                            ("rejected", "已拒绝"),
                            ("cancelled", "已取消"),
                            ("checked_in", "已签到"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("data", models.JSONField(verbose_name="表单数据")),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "报名记录",
                "verbose_name_plural": "报名记录",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="RegistrationForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="未命名表单", max_length=100, verbose_name="表单标题"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="表单描述"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "is_formio",
                    models.BooleanField(default=False, verbose_name="是否使用FormIO"),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始报名时间")),
                ("end_time", models.DateTimeField(verbose_name="结束报名时间")),
                (
                    "fields_json",
                    models.JSONField(
                        blank=True, null=True, verbose_name="表单字段JSON"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "报名表单",
                "verbose_name_plural": "报名表单",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="餐厅名称")),
                ("location", models.CharField(max_length=200, verbose_name="位置")),
                ("capacity", models.IntegerField(verbose_name="容纳人数")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=100, verbose_name="联系人"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="联系电话"),
                ),
            ],
            options={
                "verbose_name": "餐厅",
                "verbose_name_plural": "餐厅",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.CharField(max_length=20, verbose_name="房间号")),
                ("floor", models.CharField(max_length=10, verbose_name="楼层")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "可用"),
                            ("occupied", "已占用"),
                            ("maintenance", "维护中"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "房间",
                "verbose_name_plural": "房间",
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="房型名称")),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("single", "单人间"),
                            ("double", "双人间"),
                            ("suite", "套房"),
                            ("deluxe", "豪华间"),
                        ],
                        max_length=20,
                        verbose_name="房间类型",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="房价"
                    ),
                ),
                ("capacity", models.IntegerField(verbose_name="可住人数")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="房型描述"),
                ),
            ],
            options={
                "verbose_name": "房间类型",
                "verbose_name_plural": "房间类型",
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="路线名称")),
                (
                    "route_type",
                    models.CharField(
                        choices=[
                            ("airport_pickup", "机场接机"),
                            ("airport_dropoff", "机场送机"),
                            ("hotel_venue", "酒店-会场"),
                            ("custom", "自定义路线"),
                        ],
                        max_length=20,
                        verbose_name="路线类型",
                    ),
                ),
                (
                    "start_location",
                    models.CharField(max_length=200, verbose_name="起点"),
                ),
                ("end_location", models.CharField(max_length=200, verbose_name="终点")),
                ("estimated_duration", models.DurationField(verbose_name="预计用时")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="路线描述"),
                ),
            ],
            options={
                "verbose_name": "路线",
                "verbose_name_plural": "路线",
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=20, verbose_name="座位号")),
                (
                    "seat_type",
                    models.CharField(
                        choices=[
                            ("regular", "普通座位"),
                            ("vip", "VIP座位"),
                            ("speaker", "演讲者座位"),
                            ("staff", "工作人员座位"),
                        ],
                        default="regular",
                        max_length=20,
                        verbose_name="座位类型",
                    ),
                ),
                ("row", models.CharField(max_length=10, verbose_name="排号")),
                ("column", models.CharField(max_length=10, verbose_name="列号")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="是否可用"),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "座位",
                "verbose_name_plural": "座位",
                "ordering": ["row", "column"],
            },
        ),
        migrations.CreateModel(
            name="SeatAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配时间"),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "座位分配",
                "verbose_name_plural": "座位分配",
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_time", models.DateTimeField(verbose_name="出发时间")),
                ("arrival_time", models.DateTimeField(verbose_name="到达时间")),
                ("max_passengers", models.IntegerField(verbose_name="最大乘客数")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "已安排"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "行程",
                "verbose_name_plural": "行程",
            },
        ),
        migrations.CreateModel(
            name="TripRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "已登记"),
                            ("confirmed", "已确认"),
                            ("boarded", "已上车"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="registered",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "luggage_count",
                    models.IntegerField(default=0, verbose_name="行李数量"),
                ),
                (
                    "special_requirements",
                    models.TextField(blank=True, null=True, verbose_name="特殊要求"),
                ),
                (
                    "registration_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="登记时间"),
                ),
                (
                    "boarding_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上车时间"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "行程登记",
                "verbose_name_plural": "行程登记",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("bus", "大巴"), ("van", "面包车"), ("car", "轿车")],
                        max_length=20,
                        verbose_name="车辆类型",
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(max_length=20, unique=True, verbose_name="车牌号"),
                ),
                ("capacity", models.IntegerField(verbose_name="载客量")),
                (
                    "driver_name",
                    models.CharField(max_length=100, verbose_name="司机姓名"),
                ),
                (
                    "driver_phone",
                    models.CharField(max_length=20, verbose_name="司机电话"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "车辆",
                "verbose_name_plural": "车辆",
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="会场名称")),
                ("address", models.TextField(verbose_name="详细地址")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="会场描述"),
                ),
                ("capacity", models.IntegerField(verbose_name="容纳人数")),
                (
                    "floor_plan_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="venue/floor_plans/",
                        verbose_name="平面图",
                    ),
                ),
            ],
            options={
                "verbose_name": "会场",
                "verbose_name_plural": "会场",
            },
        ),
        migrations.CreateModel(
            name="VenueRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="房间名称")),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("main", "主会场"),
                            ("sub", "分会场"),
                            ("meeting", "会议室"),
                            ("rest", "休息室"),
                        ],
                        max_length=20,
                        verbose_name="房间类型",
                    ),
                ),
                ("capacity", models.IntegerField(verbose_name="容纳人数")),
                ("floor", models.CharField(max_length=50, verbose_name="所在楼层")),
                ("room_number", models.CharField(max_length=50, verbose_name="房间号")),
            ],
            options={
                "verbose_name": "会议室",
                "verbose_name_plural": "会议室",
            },
        ),
    ]
