# Generated by Django 5.1.3 on 2024-12-18 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferenceApp", "0005_registrationform_logic_rules_json"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferenceContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("organizer", "主办方"),
                            ("speaker", "演讲者"),
                            ("participant", "参会者"),
                            ("staff", "工作人员"),
                        ],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="主要联系人"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="联系人在此会议中的具体职责或其他信息",
                        verbose_name="备注",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "会议联系人",
                "verbose_name_plural": "会议联系人列表",
                "ordering": ["-is_primary", "role", "contact__user__name"],
            },
        ),
        migrations.CreateModel(
            name="ParticipantInfoChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(max_length=100, verbose_name="变更字段"),
                ),
                ("old_value", models.TextField(verbose_name="原值")),
                ("new_value", models.TextField(verbose_name="新值")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "review_comment",
                    models.TextField(blank=True, verbose_name="审核意见"),
                ),
            ],
            options={
                "verbose_name": "信息变更记录",
                "verbose_name_plural": "信息变更记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="contactperson",
            options={
                "ordering": ["-is_primary", "user__name"],
                "verbose_name": "公司联系人",
                "verbose_name_plural": "公司联系人列表",
            },
        ),
        migrations.RemoveConstraint(
            model_name="contactperson",
            name="unique_primary_contact",
        ),
        migrations.AddField(
            model_name="participant",
            name="contact_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="as_participant",
                to="conferenceApp.contactperson",
                verbose_name="关联联系人",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="info_verified",
            field=models.BooleanField(default=False, verbose_name="信息已验证"),
        ),
        migrations.AddField(
            model_name="participant",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participant_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="关联用户",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6, verbose_name="验证码"),
        ),
        migrations.AddField(
            model_name="participant",
            name="verification_code_expires",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="验证码过期时间"
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="主要联系人"),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="电话"),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="position",
            field=models.CharField(blank=True, max_length=100, verbose_name="职位"),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contactperson",
            unique_together={("user", "company")},
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(fields=["email"], name="conferenceA_email_4c2f59_idx"),
        ),
        migrations.AddField(
            model_name="conferencecontact",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_roles",
                to="conferenceApp.conference",
                verbose_name="会议",
            ),
        ),
        migrations.AddField(
            model_name="conferencecontact",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conference_roles",
                to="conferenceApp.contactperson",
                verbose_name="联系人",
            ),
        ),
        migrations.AddField(
            model_name="participantinfochange",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_changes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="提交人",
            ),
        ),
        migrations.AddField(
            model_name="participantinfochange",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="info_changes",
                to="conferenceApp.participant",
                verbose_name="参会人",
            ),
        ),
        migrations.AddField(
            model_name="participantinfochange",
            name="reviewed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_changes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conferencecontact",
            unique_together={("contact", "conference", "role")},
        ),
    ]
