# Generated by Django 5.1.3 on 2024-12-18 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferenceApp", "0006_conferencecontact_participantinfochange_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="标签名称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "联系人标签",
                "verbose_name_plural": "联系人标签列表",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="contactperson",
            name="name",
            field=models.CharField(default="", max_length=100, verbose_name="姓名"),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="contactperson",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="contacts",
                to="conferenceApp.contacttag",
                verbose_name="标签",
            ),
        ),
    ]
