# Generated by Django 5.1.3 on 2024-12-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conferenceApp", "0007_add_contact_tag_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactperson",
            options={
                "ordering": ["-is_primary", "user__email"],
                "verbose_name": "公司联系人",
                "verbose_name_plural": "公司联系人列表",
            },
        ),
        migrations.RemoveField(
            model_name="contactperson",
            name="name",
        ),
    ]
