version: '3'

services:
  mail:
    image: mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.gysdh.chat
    domainname: gysdh.chat
    ports:
      - "25:25"    # SMTP
      - "465:465"  # SMTPS
      - "587:587"  # Submission
      - "993:993"  # IMAPS
    volumes:
      - ./maildata:/var/mail
      - ./mailstate:/var/mail-state
      - ./maillogs:/var/log/mail
      - ./config:/tmp/docker-mailserver
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - POSTMASTER_ADDRESS=postmaster@gysdh.chat
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/docker-mailserver/cert/fullchain.pem
      - SSL_KEY_PATH=/tmp/docker-mailserver/cert/privkey.pem
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
