# Generated by Django 5.1.3 on 2024-12-21 06:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gysdhChatApp", "0002_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="支持富文本格式", verbose_name="公告内容"
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="注意事项内容"),
        ),
    ]
