# Generated by Django 5.1.3 on 2024-12-21 07:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gysdhChatApp", "0003_update_to_ckeditor5"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="邮件内容"),
        ),
    ]
